### PR TITLE
Snapshots inside tables are broken

### LINKED ISSUE #38: Snapshots inside tables are breaking
```diff
- Expect
+ Received

- <tr>
-   <td>
-     asdf
-   </td>
-   <td>
-     qwer
-   </td>
- </tr>
+ asdf
+
+
+ qwer
```

### PR DESCRIPTION
**Pull request by TheJaredWilcurt**
[Coverage Status](https://coveralls.io/github/tjw-lint/jest-serializer-vue-tjw?branch=tables)

* [x] Functionality
* [x] Tests
* [x] Documentation
* [x] Version bump
* [x] ~~Update deps~~

* * *

Fixes #38

### CODE REVIEW

File: tests/components/Zoom.vue [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+    </table>
+  </div>
+</template>
+
+<script>
+export default {
+  name: 'Zoom'
+};
+</script>
+
```
Comment (TheJaredWilcurt) [inline tests/components/Zoom.vue]:
```suggestion
```
